# docker-compose.yml
version: '3'
services:
  vk-lftable-dev:
    image: vk-lftable-dev
    volumes:
        - ./log:/vk-lftable/log
        - ./db:/vk-lftable/db

    build:
      context: .
      dockerfile: Dockerfile
    ports:
            - 127.0.0.1:6000:5000
